spring: 
  application: 
    name: countryApp-client 
server: 
  port: 6060
info:
  description: countryApp
  name: Display all countries

eureka: 
  client: 
    serviceUrl: 
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} 
  instance: 
    hostname: localhost 
    preferIpAddress: true
    status-page-url-path: http://${eureka.instance.hostname}:${server.port}/t1/getAllCountries
  register-with-eureka: false
  fetch-registry: false
