spring: 
  application: 
    name: cityApp-client 
server: 
  port: 9080
info:
  description: cityApp
  name: Display all cities for each country

eureka: 
  client: 
    serviceUrl: 
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} 
  instance: 
    hostname: localhost 
    preferIpAddress: true
    status-page-url-path: http://${eureka.instance.hostname}:${server.port}/t1/getAll
  register-with-eureka: false
  fetch-registry: false
